### ISSUE TITLE
Ensure compatibility with AWS S3

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/karton#64] opened 2020-12-16 17:10 UTC

**Comment by alex-ilgayev** [comment] 2021-09-10 11:01
I would add an option for IAM authentication without credentials similar to this recently merged PR:
https://github.com/CERT-Polska/mwdb-core/pull/443

**Comment by alex-ilgayev** [comment] 2021-12-22 09:24
Hey @nazywam 
We are working quite a while with S3 instead of Minio, and it is working as intended.
So I suggest you can close this issue.

**Comment by nazywam** [comment] 2021-12-22 09:34
Will do, thanks!

**Closed by nazywam** 2021-12-22 09:34 UTC
Labels: enhancement
